# Generated by Django 4.1.3 on 2024-08-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trial.authentic'),
            preserve_default=False,
        ),
    ]
