# Generated by Django 4.1.3 on 2024-07-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_alter_authentic_email_alter_authentic_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentic',
            name='reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
