# Generated by Django 4.1.3 on 2024-08-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentic',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
