# Generated by Django 4.1.3 on 2024-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0003_authentic_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentic',
            name='verification_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
