# Generated by Django 4.1.3 on 2024-07-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0003_authentic_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentic',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authentic',
            name='verification_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
