# Generated by Django 4.1.3 on 2024-08-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0005_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authentic_token',
            field=models.ForeignKey(default='token', on_delete=django.db.models.deletion.CASCADE, to='trial.authentic'),
        ),
    ]
