# Generated by Django 4.1.3 on 2024-08-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0008_alter_customuser_authentic_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='authentic_token',
        ),
    ]
