# Generated by Django 4.1.3 on 2024-08-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0011_remove_customuser_authentic_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
