# Generated by Django 4.1.3 on 2024-08-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0013_customuser_authentic_reset_token_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
