# Generated by Django 4.1.3 on 2024-08-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0014_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentic',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='authentic',
            name='reset_token_expiry',
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_token', models.CharField(blank=True, max_length=32, null=True)),
                ('reset_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.authentic')),
            ],
        ),
    ]
